//! Lua-scripted visualizer.
//!
//! A script defines `function render(width, height, left, right)`, called
//! once per frame with the newly-arrived stereo samples as two flat,
//! 1-indexed tables of numbers. It draws with four host-provided functions:
//!
//! * `clear({r, g, b})`
//! * `line(x0, y0, x1, y1, {r, g, b [, a]})`
//! * `rect(x0, y0, x1, y1, {r, g, b [, a]})`
//! * `pixel(x, y, {r, g, b [, a]})`
//!
//! Colors are plain Lua tables. `a` is opacity 0.0..1.0, default 1.0 (an
//! opaque draw overwrites; a translucent one alpha-blends over what's there).
//! The interpreted cost of reading a color table is paid once per draw call
//! (queued as a packed `u32`), never once per pixel.
//!
//! Other host functions:
//! * `fft_left(left)` / `fft_right(right)`, windowed magnitude spectrum
//!   (length `spectrum.rs`'s `FFT_SIZE / 2`) of a channel's last ~1024
//!   samples, computed in Rust so scripts stay fast without their own FFT.
//! * `active_notes()` / `upcoming_notes()`, notes held now / changing within
//!   `NOTE_LOOKAHEAD` seconds.
//! * `midi_channels()`, the channels the current file uses.
//! * `channel_enabled(channel)`, the GUI's per-channel toggle (true if
//!   nothing is detected yet).
//! * `set_channel_enabled(channel, enabled)`, a script can mute/unmute a
//!   channel too, not just read its state (e.g. a game script silencing the
//!   channel for a dead player). Goes through the same command as the GUI's
//!   checkboxes, so it can't disable the last remaining enabled channel
//!   either.
//! * `playback()`, transport state: `{position, length, speed, paused,
//!   finished, loop_enabled}`. The thing to check before writing into a
//!   scrolling history buffer, so pausing freezes the picture instead of
//!   scrolling through a frozen spectrum.
//! * `log(message)`, appends to this script's log, shown in the Settings
//!   popup. Identical consecutive messages collapse into one entry with a
//!   count, so a `log()` called every frame doesn't flood the pane.
//! * `DT`, seconds since the previous `render` call (0.0 on the first,
//!   capped at 0.25).
//! * Input: `mouse()`, `mouse_delta()`, `scroll()`,
//!   `mouse_down/pressed/released([button])`, `key_down/pressed/released(name)`,
//!   `has_focus()`, `display_mode()`. Mouse while the pointer is over the
//!   visualizer, keys while it has focus; Escape is never reported.
//! * Cursor: `set_cursor_visible(visible)` (applies over the visualizer) and
//!   `set_cursor_locked(locked)` (keeps it on screen, dedicated fullscreen
//!   only).
//!
//! Settings: a script can expose typed, user-editable values via
//! `setting_bool/int/float/color/string/selection(key, ...)`, called every
//! frame, the first call each compile registers the descriptor (default,
//! range, options); every call after that just returns the live value, so
//! editing a slider in the Script Settings tab updates the running script
//! immediately, without a recompile or disturbing any history the script is
//! keeping. Values persist to `<script>.lua.settings.json` next to the
//! script and are re-applied on the next load, falling back to the script's
//! own default for anything the sidecar doesn't have.
//!
//! Live reload: [`LuaVisualizer::set_source`] recompiles against a fresh Lua
//! VM. A script that fails to compile, or doesn't define `render`, leaves the
//! previously working script (if any) running, the error is recorded but
//! never blanks the view, so a mid-edit typo doesn't stop playback.

use std::cell::RefCell;
use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};
use std::rc::Rc;
use std::time::Instant;

use anyhow::Result;
use eframe::egui;
use mlua::{Function, Lua, LuaOptions, StdLib, Table, Value};
use serde::Deserialize;

use crate::config::{config_dir, nice_name};
use crate::engine::{EngineView, NOTE_LOOKAHEAD_SECS};
use crate::spectrum::SpectrumAnalyzer;
use crate::visualizer::{
    ActiveNote, CursorRequest, NoteChange, NotesSnapshot, RESERVED_KEYS, StereoFrame, Visualizer,
    VisualizerInput,
};

// DROPPED_SCRIPTS and UNDROPPED_SCRIPTS: &[(&str, &str)] of (file name,
// contents), generated by build.rs from whatever .lua files are actually in
// assets/visualizers/dropped and assets/visualizers/undropped, see that
// file. Adding, removing, or renaming a bundled script is a file move in
// assets/, not an edit here.
include!(concat!(env!("OUT_DIR"), "/bundled_scripts.rs"));

const BLANK_SCRIPT_TEMPLATE: &str = "\
-- New visualizer. `render` is called once per frame with the window size
-- and the new stereo samples (flat, 1-indexed tables) since the last frame.
--
-- Draw with clear/line/rect/pixel; color tables take an optional `a` (0..1).
--   clear({r,g,b})  line(x0,y0,x1,y1,{r,g,b,a})  rect(...)  pixel(x,y,{r,g,b,a})
-- fft_left(left) / fft_right(right)     magnitude spectrum, computed in Rust
-- active_notes() / upcoming_notes()     notes held now / changing soon
-- midi_channels() / channel_enabled(c)  the file's channels and their toggles
-- set_channel_enabled(c, enabled)       mute/unmute a channel from the script
-- playback()                            transport state (paused, position, ...)
-- log(message) / DT                     debug log, seconds since last frame
-- mouse() / key_down('a') / has_focus()  input over the visualizer (see Docs)
-- setting_bool/int/float/color/string/selection(key, ...)  user-editable values

function render(width, height, left, right)
    clear({ r = 16, g = 16, b = 24 })
end
";

/// The folder user (and bundled default) visualizer scripts live in,
/// creating it and seeding the defaults into it on first use only, a
/// `.seeded` marker (distinct from the scripts' own presence) remembers that
/// the one-time seed already happened, so a bundled default the user deletes
/// stays deleted on later launches instead of quietly reappearing. "Restore
/// default" (`bundled_default`) is the deliberate way to bring one back.
pub fn scripts_dir() -> Result<PathBuf> {
    let dir = config_dir()?.join("visualizers");
    fs::create_dir_all(&dir)?;

    let marker = dir.join(".seeded");
    if !marker.exists() {
        for &(name, contents) in DROPPED_SCRIPTS {
            seed_default(&dir, name, contents)?;
        }
        fs::write(&marker, "")?;
    }

    Ok(dir)
}

fn seed_default(dir: &Path, name: &str, contents: &str) -> Result<()> {
    let path = dir.join(name);
    if !path.exists() {
        fs::write(path, contents)?;
    }
    Ok(())
}

/// Every `.lua` file directly inside `dir`, sorted by name.
pub fn list_scripts(dir: &Path) -> Vec<PathBuf> {
    let mut scripts: Vec<PathBuf> = fs::read_dir(dir)
        .map(|read_dir| {
            read_dir
                .flatten()
                .map(|entry| entry.path())
                .filter(|path| path.extension().and_then(|e| e.to_str()) == Some("lua"))
                .collect()
        })
        .unwrap_or_default();
    scripts.sort();
    scripts
}

/// Starting points offered by the "New" button: a blank script, then every
/// bundled script, dropped (handy as a base to fork) and undropped (API
/// demos) alike. Display names are the bare file stem, same convention
/// `display_name`/`nice_name` already use for a script's own name elsewhere.
pub fn new_script_templates() -> Vec<(&'static str, &'static str)> {
    let mut templates = vec![("Blank", BLANK_SCRIPT_TEMPLATE)];
    for &(name, contents) in DROPPED_SCRIPTS.iter().chain(UNDROPPED_SCRIPTS) {
        templates.push((name.strip_suffix(".lua").unwrap_or(name), contents));
    }
    templates
}

/// Create `<dir>/untitled-N.lua` (picking the first free `N`) from `content`
/// and return its path.
pub fn new_script_from_template(dir: &Path, content: &str) -> Result<PathBuf> {
    let mut n = 1;
    let path = loop {
        let candidate = dir.join(format!("untitled-{n}.lua"));
        if !candidate.exists() {
            break candidate;
        }
        n += 1;
    };
    fs::write(&path, content)?;
    Ok(path)
}

pub fn display_name(path: &Path) -> String {
    nice_name(path)
}

/// The current embedded source for an auto-seeded (dropped) script, by file
/// name. `seed_default` only writes these when missing, so this is how the
/// app offers a "restore" when a bundled script has drifted from the shipped
/// one. Undropped scripts never get auto-seeded under their own name (`New`
/// always writes to a fresh `untitled-N.lua`), so there's nothing for their
/// filename to drift from, scoped to `DROPPED_SCRIPTS` only.
pub fn bundled_default(file_name: &str) -> Option<&'static str> {
    DROPPED_SCRIPTS.iter().find(|&&(name, _)| name == file_name).map(|&(_, contents)| contents)
}

#[derive(Clone, Copy)]
enum DrawCommand {
    Clear(u32),
    Line { x0: f32, y0: f32, x1: f32, y1: f32, color: u32 },
    Rect { x0: f32, y0: f32, x1: f32, y1: f32, color: u32 },
    Pixel { x: i32, y: i32, color: u32 },
}

// --- settings -----------------------------------------------------------

/// A setting's current (or default) value. The type is always known from
/// context (the matching [`SettingKind`] variant), so there's no separate
/// discriminant check needed beyond the `match` arms already doing one.
#[derive(Clone, Debug)]
pub enum SettingValue {
    Bool(bool),
    Int(i64),
    Float(f64),
    /// Plain RGB, no alpha, draw-call alpha is a separate, per-call concern.
    Color([u8; 3]),
    String(String),
    /// Selected option labels, oldest-selected first, that order is what
    /// lets a new pick past `max_selections` evict the oldest one rather
    /// than needing a separate disabled-checkbox state.
    Selection(Vec<String>),
}

#[derive(Clone, Debug)]
pub enum SettingKind {
    Bool,
    Int { min: i64, max: i64 },
    Float { min: f64, max: f64 },
    Color,
    String,
    Selection { options: Vec<String>, max_selections: usize },
}

#[derive(Clone, Debug)]
pub struct SettingDescriptor {
    pub key: String,
    pub kind: SettingKind,
    pub value: SettingValue,
}

/// Registered settings for one compiled script, seeded from the sidecar file
/// (if any) and filled in as the script's `setting_*` calls register each
/// one. Lives inside [`Compiled`], a fresh store per successful compile, so
/// switching scripts (or a script changing its own option list) can't leave
/// stale descriptors behind.
#[derive(Default)]
struct SettingsStore {
    descriptors: Vec<SettingDescriptor>,
    /// Sidecar values not yet claimed by a registering `setting_*` call.
    pending: HashMap<String, serde_json::Value>,
}

impl SettingsStore {
    fn find(&self, key: &str) -> Option<&SettingDescriptor> {
        self.descriptors.iter().find(|d| d.key == key)
    }

    fn get_or_register_bool(&mut self, key: &str, default: bool) -> bool {
        if let Some(SettingValue::Bool(v)) = self.find(key).map(|d| &d.value) {
            return *v;
        }
        let initial = self.pending.get(key).and_then(|v| v.as_bool()).unwrap_or(default);
        self.descriptors.push(SettingDescriptor {
            key: key.to_string(),
            kind: SettingKind::Bool,
            value: SettingValue::Bool(initial),
        });
        initial
    }

    fn get_or_register_int(&mut self, key: &str, default: i64, min: i64, max: i64) -> i64 {
        let (min, max) = (min.min(max), min.max(max));
        if let Some(SettingValue::Int(v)) = self.find(key).map(|d| &d.value) {
            return *v;
        }
        let initial = self
            .pending
            .get(key)
            .and_then(serde_json::Value::as_i64)
            .map(|v| v.clamp(min, max))
            .unwrap_or_else(|| default.clamp(min, max));
        self.descriptors.push(SettingDescriptor {
            key: key.to_string(),
            kind: SettingKind::Int { min, max },
            value: SettingValue::Int(initial),
        });
        initial
    }

    fn get_or_register_float(&mut self, key: &str, default: f64, min: f64, max: f64) -> f64 {
        let (min, max) = (min.min(max), min.max(max));
        if let Some(SettingValue::Float(v)) = self.find(key).map(|d| &d.value) {
            return *v;
        }
        let initial = self
            .pending
            .get(key)
            .and_then(serde_json::Value::as_f64)
            .map(|v| v.clamp(min, max))
            .unwrap_or_else(|| default.clamp(min, max));
        self.descriptors.push(SettingDescriptor {
            key: key.to_string(),
            kind: SettingKind::Float { min, max },
            value: SettingValue::Float(initial),
        });
        initial
    }

    fn get_or_register_color(&mut self, key: &str, default: [u8; 3]) -> [u8; 3] {
        #[derive(Deserialize)]
        struct ColorJson {
            r: u8,
            g: u8,
            b: u8,
        }

        if let Some(SettingValue::Color(v)) = self.find(key).map(|d| &d.value) {
            return *v;
        }
        let initial = self
            .pending
            .get(key)
            .and_then(|v| serde_json::from_value::<ColorJson>(v.clone()).ok())
            .map(|c| [c.r, c.g, c.b])
            .unwrap_or(default);
        self.descriptors.push(SettingDescriptor {
            key: key.to_string(),
            kind: SettingKind::Color,
            value: SettingValue::Color(initial),
        });
        initial
    }

    fn get_or_register_string(&mut self, key: &str, default: &str) -> String {
        if let Some(SettingValue::String(v)) = self.find(key).map(|d| &d.value) {
            return v.clone();
        }
        let initial = self
            .pending
            .get(key)
            .and_then(|v| v.as_str())
            .map(str::to_string)
            .unwrap_or_else(|| default.to_string());
        self.descriptors.push(SettingDescriptor {
            key: key.to_string(),
            kind: SettingKind::String,
            value: SettingValue::String(initial.clone()),
        });
        initial
    }

    fn get_or_register_selection(
        &mut self,
        key: &str,
        options: Vec<String>,
        defaults: Vec<String>,
        max_selections: usize,
    ) -> Vec<String> {
        if let Some(SettingValue::Selection(v)) = self.find(key).map(|d| &d.value) {
            return v.clone();
        }
        let max_selections = max_selections.max(1);
        let valid_defaults: Vec<String> =
            defaults.into_iter().filter(|d| options.contains(d)).take(max_selections).collect();
        let from_sidecar = self.pending.get(key).and_then(|v| v.as_array()).map(|arr| {
            arr.iter()
                .filter_map(|v| v.as_str().map(str::to_string))
                .filter(|s| options.contains(s))
                .take(max_selections)
                .collect::<Vec<_>>()
        });
        let initial = from_sidecar.filter(|v| !v.is_empty()).unwrap_or(valid_defaults);
        self.descriptors.push(SettingDescriptor {
            key: key.to_string(),
            kind: SettingKind::Selection { options, max_selections },
            value: SettingValue::Selection(initial.clone()),
        });
        initial
    }

    /// Apply a value edited through the Script Settings tab. Selection values are
    /// defensively truncated (keeping the most recent) in case a caller
    /// hands back more than `max_selections`, the UI itself should never do
    /// this, but a setting is cheap to protect either way.
    fn set(&mut self, key: &str, value: SettingValue) {
        if let Some(d) = self.descriptors.iter_mut().find(|d| d.key == key) {
            if let (SettingKind::Selection { max_selections, .. }, SettingValue::Selection(mut v)) =
                (&d.kind, value.clone())
            {
                if v.len() > *max_selections {
                    v = v.split_off(v.len() - *max_selections);
                }
                d.value = SettingValue::Selection(v);
            } else {
                d.value = value;
            }
        }
    }
}

fn sidecar_path(script_path: &Path) -> PathBuf {
    let mut name = script_path.as_os_str().to_os_string();
    name.push(".settings.json");
    PathBuf::from(name)
}

fn load_pending_settings(path: Option<&Path>) -> HashMap<String, serde_json::Value> {
    let Some(path) = path else { return HashMap::new() };
    fs::read_to_string(sidecar_path(path))
        .ok()
        .and_then(|s| serde_json::from_str(&s).ok())
        .unwrap_or_default()
}

fn save_sidecar(script_path: &Path, store: &SettingsStore) {
    let map: serde_json::Map<String, serde_json::Value> = store
        .descriptors
        .iter()
        .map(|d| (d.key.clone(), setting_value_to_json(&d.value)))
        .collect();
    if let Ok(json) = serde_json::to_string_pretty(&serde_json::Value::Object(map)) {
        let _ = fs::write(sidecar_path(script_path), json);
    }
}

fn setting_value_to_json(v: &SettingValue) -> serde_json::Value {
    match v {
        SettingValue::Bool(b) => serde_json::Value::Bool(*b),
        SettingValue::Int(i) => serde_json::Value::from(*i),
        SettingValue::Float(f) => serde_json::Value::from(*f),
        SettingValue::Color([r, g, b]) => serde_json::json!({ "r": r, "g": g, "b": b }),
        SettingValue::String(s) => serde_json::Value::String(s.clone()),
        SettingValue::Selection(items) => serde_json::Value::from(items.clone()),
    }
}

// --- log history ----------------------------------------------------------

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum LogLevel {
    Info,
    Error,
}

#[derive(Clone, Debug)]
pub struct LogEntry {
    pub level: LogLevel,
    pub message: String,
    /// How many times this exact message repeated immediately in a row.
    pub count: u32,
}

/// Longest `DT` a script ever sees, in seconds (see `render`).
const MAX_DT: f64 = 0.25;

const MAX_LOG_ENTRIES: usize = 200;
const MAX_LOG_MESSAGE_LEN: usize = 500;

/// A script's `log()` output plus its own runtime errors, in one
/// chronological, browser-console-style list: an entry identical to the most
/// recent one just bumps its count instead of repeating, so a `log()` called
/// every frame doesn't flood the pane. Lives inside [`Compiled`], fresh per
/// successful compile, so switching scripts starts from a clean slate.
#[derive(Default)]
struct LogHistory {
    entries: Vec<LogEntry>,
}

impl LogHistory {
    fn push(&mut self, level: LogLevel, mut message: String) {
        if message.len() > MAX_LOG_MESSAGE_LEN {
            message.truncate(MAX_LOG_MESSAGE_LEN);
            message.push_str("...");
        }
        if let Some(last) = self.entries.last_mut()
            && last.level == level
            && last.message == message
        {
            last.count += 1;
            return;
        }
        self.entries.push(LogEntry { level, message, count: 1 });
        if self.entries.len() > MAX_LOG_ENTRIES {
            let excess = self.entries.len() - MAX_LOG_ENTRIES;
            self.entries.drain(0..excess);
        }
    }
}

// --- debug locals ---------------------------------------------------------
//
// `debug_locals([label])`, a script calls it by name at whatever specific
// point its author wants a snapshot from, e.g.
// `debug_locals("after collision check")` deep inside a loop, which is the
// thing a fixed "show me the module's top-level state" view can't do. It
// reads real Lua locals via the debug C API (lua_getstack/lua_getlocal on
// the calling frame), mlua's safe API has no equivalent, since locals
// (unlike globals) aren't a Lua *value* reachable through any table, just
// stack slots in a running frame.
//
// An earlier version of this also had an editor gutter with a clickable
// line marker that injected the call automatically, so you never had to
// type it, dropped (not just undocumented) after it turned out to be
// laggy (a button per source line adds up) and gutter/text alignment in
// egui's TextEdit is its own can of worms. Calling it by hand is the
// whole interface now.

/// One entry in a `debug_locals()` snapshot's variable tree.
#[derive(Clone, Debug)]
pub struct DebugVar {
    pub name: String,
    /// A short rendering of the value; for a table, "table (N entries)".
    pub value: String,
    pub children: Vec<DebugVar>,
}

/// `debug_locals()`'s most recent result: the label it was called with (if
/// any) plus the locals in scope at that call site.
#[derive(Clone, Debug, Default)]
pub struct DebugSnapshot {
    pub label: Option<String>,
    pub vars: Vec<DebugVar>,
}

/// Depth/breadth caps so a huge or self-referential table (snake.lua's
/// `occ`, say) can't make one `debug_locals()` call expensive or hang.
const MAX_DEBUG_DEPTH: usize = 4;
const MAX_DEBUG_ENTRIES: usize = 200;
/// Lua caps a frame's visible locals well below this in practice; it's just
/// a hard backstop against ever looping on a malformed debug frame.
const MAX_DEBUG_LOCALS: std::ffi::c_int = 200;

/// Reads the locals of whatever Lua function is one frame up the call stack
/// from here, i.e. the script code that's in the middle of calling
/// `debug_locals()` right now. Safety: `exec_raw_lua` hands us the same
/// `lua_State` mlua itself is driving, from inside a callback mlua invoked
/// *from* that exact Lua call, so level 1 is guaranteed to exist and be a
/// Lua (not C) frame; `lua_getlocal`'s contract is to push the value it
/// names and return null once names run out, which is what the loop below
/// assumes.
fn capture_caller_locals(lua: &Lua) -> Vec<DebugVar> {
    lua.exec_raw_lua(|raw| unsafe {
        let state = raw.state();
        let mut ar: mlua::ffi::lua_Debug = std::mem::zeroed();
        if mlua::ffi::lua_getstack(state, 1, &mut ar) == 0 {
            return Vec::new();
        }

        let mut vars = Vec::new();
        for n in 1..=MAX_DEBUG_LOCALS {
            let name_ptr = mlua::ffi::lua_getlocal(state, &ar, n);
            if name_ptr.is_null() {
                break;
            }
            let name = std::ffi::CStr::from_ptr(name_ptr).to_string_lossy().into_owned();
            // lua_getlocal already pushed the value; read (and pop) it
            // regardless of whether we keep it, to leave the stack as we
            // found it.
            let value: Value = raw.pop().unwrap_or(Value::Nil);
            // Lua names its own internal temporaries (loop control state
            // etc.) with a leading '(', not something the script wrote.
            if !name.starts_with('(') {
                vars.push(describe_value(&name, &value, 0));
            }
        }
        vars
    })
}

fn describe_value(name: &str, value: &Value, depth: usize) -> DebugVar {
    if let Value::Table(table) = value
        && depth < MAX_DEBUG_DEPTH
    {
        let mut children = Vec::new();
        for pair in table.pairs::<Value, Value>() {
            let Ok((key, val)) = pair else { continue };
            if children.len() >= MAX_DEBUG_ENTRIES {
                children.push(DebugVar {
                    name: "...".to_string(),
                    value: "(truncated)".to_string(),
                    children: Vec::new(),
                });
                break;
            }
            children.push(describe_value(&describe_scalar(&key), &val, depth + 1));
        }
        return DebugVar { name: name.to_string(), value: format!("table ({} entries)", children.len()), children };
    }
    DebugVar { name: name.to_string(), value: describe_scalar(value), children: Vec::new() }
}

fn describe_scalar(value: &Value) -> String {
    match value {
        Value::Nil => "nil".to_string(),
        Value::Boolean(b) => b.to_string(),
        Value::Integer(i) => i.to_string(),
        Value::Number(n) => n.to_string(),
        Value::String(s) => format!("{:?}", s.to_string_lossy()),
        Value::Function(_) => "<function>".to_string(),
        Value::Table(_) => "<table>".to_string(), // only hit past MAX_DEBUG_DEPTH
        _ => "<value>".to_string(),
    }
}

/// Everything tied to one successfully-compiled script: its own Lua VM (a
/// fresh one per reload, so stale globals from a previous version of the
/// script can't linger), the `render` function, the draw-command queue its
/// draw calls feed, and its settings/log state, all reset together on
/// reload, since they're meaningless carried over to a different script.
struct Compiled {
    /// The source this was compiled from, so `restart` can run the same
    /// script again even after a newer edit failed to compile.
    source: String,
    lua: Lua,
    render: Function,
    commands: Rc<RefCell<Vec<DrawCommand>>>,
    settings: Rc<RefCell<SettingsStore>>,
    log: Rc<RefCell<LogHistory>>,
    /// `(channel, enabled)` requests queued by `set_channel_enabled`, drained
    /// by the host once per frame and turned into real `AudioCommand`s, the
    /// script can't touch the engine directly, just ask.
    channel_requests: Rc<RefCell<Vec<(u8, bool)>>>,
    /// The most recent `debug_locals()` snapshot: an optional label plus
    /// whatever was in scope at that call site. `None` until the script
    /// calls it at least once.
    debug_snapshot: Rc<RefCell<Option<DebugSnapshot>>>,
    /// What the script asked for via `set_cursor_visible`/`set_cursor_locked`.
    /// Per script: a newly loaded one starts with a normal cursor.
    cursor: Rc<RefCell<CursorRequest>>,
}

pub struct LuaVisualizer {
    sample_rate: u32,
    path: Option<PathBuf>,
    source: String,
    compiled: Option<Compiled>,
    /// Set when the most recent `set_source` call failed (to compile, or —
    /// from `set_source_and_save`, to write to disk); cleared the next time
    /// a `set_source` call succeeds outright. Deliberately independent of
    /// `runtime_error`: the old script kept running after a bad edit might
    /// go on rendering perfectly fine, and a successful frame from it
    /// shouldn't make the bad edit's error vanish before it's even been
    /// read, that was the actual bug, not just overly-transient UI.
    compile_error: Option<String>,
    /// Set from the outcome of the most recent `render` call; cleared the
    /// next time one succeeds. This one *is* meant to be that transient —
    /// it reflects whether the script is erroring right now.
    runtime_error: Option<String>,
    spectrum_left: Rc<RefCell<SpectrumAnalyzer>>,
    spectrum_right: Rc<RefCell<SpectrumAnalyzer>>,
    /// The current frame's note info, shared with the `active_notes()` /
    /// `upcoming_notes()` Lua functions.
    notes: Rc<RefCell<NotesSnapshot>>,
    /// The current frame's transport state, shared with `playback()`.
    /// Ground truth, not script-specific, unlike `settings`/`log`, it
    /// persists across recompiles rather than resetting per script.
    playback: Rc<RefCell<EngineView>>,
    /// The current frame's mouse/keyboard input, shared with the input
    /// functions. Ground truth like `playback`, so it outlives recompiles.
    input: Rc<RefCell<VisualizerInput>>,
    last_render_instant: Option<Instant>,
}

impl LuaVisualizer {
    pub fn new(source: String, path: Option<PathBuf>, sample_rate: u32) -> Self {
        let mut visualizer = Self {
            sample_rate,
            path,
            source: String::new(),
            compiled: None,
            compile_error: None,
            runtime_error: None,
            spectrum_left: Rc::new(RefCell::new(SpectrumAnalyzer::new())),
            spectrum_right: Rc::new(RefCell::new(SpectrumAnalyzer::new())),
            notes: Rc::new(RefCell::new(NotesSnapshot::default())),
            playback: Rc::new(RefCell::new(EngineView::default())),
            input: Rc::new(RefCell::new(VisualizerInput::default())),
            last_render_instant: None,
        };
        visualizer.set_source(source);
        visualizer
    }

    pub fn path(&self) -> Option<&Path> {
        self.path.as_deref()
    }

    pub fn set_path(&mut self, path: Option<PathBuf>) {
        self.path = path;
    }

    /// The error to show right now: a standing compile/save error from the
    /// last edit takes priority (it won't clear on its own, see
    /// `compile_error`'s docs), falling back to the current frame's runtime
    /// error if there isn't one. `None` means the running script is healthy.
    pub fn error(&self) -> Option<&str> {
        self.compile_error.as_deref().or(self.runtime_error.as_deref())
    }

    /// The active script's registered settings, in declaration order.
    pub fn settings(&self) -> Vec<SettingDescriptor> {
        self.compiled.as_ref().map(|c| c.settings.borrow().descriptors.clone()).unwrap_or_default()
    }

    /// Apply a value edited through the Script Settings tab and persist it to the
    /// script's sidecar file (if it has one, a script with no path yet,
    /// e.g. mid-creation, just keeps the change in memory).
    pub fn set_setting(&mut self, key: &str, value: SettingValue) {
        let Some(compiled) = &self.compiled else { return };
        compiled.settings.borrow_mut().set(key, value);
        if let Some(path) = &self.path {
            save_sidecar(path, &compiled.settings.borrow());
        }
    }

    /// The active script's log + runtime-error history, oldest first.
    pub fn log_entries(&self) -> Vec<LogEntry> {
        self.compiled.as_ref().map(|c| c.log.borrow().entries.clone()).unwrap_or_default()
    }

    pub fn clear_log(&mut self) {
        if let Some(compiled) = &self.compiled {
            compiled.log.borrow_mut().entries.clear();
        }
    }

    /// The most recent `debug_locals()` snapshot, if the script has ever
    /// called it since the last compile.
    pub fn debug_snapshot(&self) -> Option<DebugSnapshot> {
        self.compiled.as_ref().and_then(|c| c.debug_snapshot.borrow().clone())
    }

    /// Channel mute/unmute requests the script made via `set_channel_enabled`
    /// since the last call, oldest first. The caller (the GUI) is expected to
    /// turn each into an `AudioCommand::SetChannelEnabled`.
    pub fn take_channel_requests(&mut self) -> Vec<(u8, bool)> {
        let Some(compiled) = &self.compiled else { return Vec::new() };
        compiled.channel_requests.borrow_mut().drain(..).collect()
    }

    /// Recompile against `new_source` on a fresh Lua VM. On success the new
    /// script takes over immediately; on failure the error is recorded (and
    /// also logged against the still-running old script, if there is one —
    /// "your last edit didn't take" is as much a fact about that script's
    /// history as a runtime error would be) and whatever script was
    /// previously running keeps running.
    pub fn set_source(&mut self, new_source: String) {
        self.source = new_source;
        let pending_settings = load_pending_settings(self.path.as_deref());
        match compile(
            &self.source,
            self.sample_rate,
            &self.spectrum_left,
            &self.spectrum_right,
            &self.notes,
            &self.playback,
            &self.input,
            pending_settings,
        ) {
            Ok(compiled) => {
                self.compiled = Some(compiled);
                self.compile_error = None;
            }
            Err(e) => {
                if let Some(compiled) = &self.compiled {
                    compiled.log.borrow_mut().push(LogLevel::Error, format!("compile error: {e}"));
                }
                self.compile_error = Some(e);
            }
        }
    }

    /// Start the running script over from scratch: a fresh Lua VM running
    /// the same source, settings re-read from its sidecar, all of its own
    /// state (history, scores, ...) gone. Restarts what's actually running,
    /// not the latest edit, which might not compile; an error from the
    /// latest edit stays reported. Returns false if nothing is running.
    pub fn restart(&mut self) -> bool {
        let Some(source) = self.compiled.as_ref().map(|c| c.source.clone()) else {
            return false;
        };
        let pending_settings = load_pending_settings(self.path.as_deref());
        match compile(
            &source,
            self.sample_rate,
            &self.spectrum_left,
            &self.spectrum_right,
            &self.notes,
            &self.playback,
            &self.input,
            pending_settings,
        ) {
            Ok(compiled) => {
                self.compiled = Some(compiled);
                self.runtime_error = None;
                self.last_render_instant = None;
                true
            }
            // Can't really happen (it compiled before), but if it does, the
            // old VM just keeps running.
            Err(e) => {
                if let Some(compiled) = &self.compiled {
                    compiled.log.borrow_mut().push(LogLevel::Error, format!("restart failed: {e}"));
                }
                false
            }
        }
    }

    /// Write `new_source` to this script's file (if it has one) and apply it.
    pub fn set_source_and_save(&mut self, new_source: String) {
        let save_error = self.path.as_ref().and_then(|path| {
            fs::write(path, &new_source)
                .err()
                .map(|e| format!("failed to save {}: {e}", path.display()))
        });
        self.set_source(new_source);
        // Computed before `set_source` (which would otherwise overwrite it
        // the moment the script itself compiles fine) and reapplied after,
        // merged with whatever compile error that call left behind.
        if let Some(save_error) = save_error {
            self.compile_error = Some(match self.compile_error.take() {
                Some(compile_error) => format!("{save_error}\n{compile_error}"),
                None => save_error,
            });
        }
    }
}

impl Visualizer for LuaVisualizer {
    fn render(
        &mut self,
        buffer: &mut [u32],
        width: usize,
        height: usize,
        samples: &[StereoFrame],
        notes: &NotesSnapshot,
        playback: &EngineView,
        input: &VisualizerInput,
    ) {
        buffer.fill(0);
        *self.notes.borrow_mut() = notes.clone();
        *self.playback.borrow_mut() = playback.clone();
        *self.input.borrow_mut() = input.clone();

        let now = Instant::now();
        // Capped, so a stretch of not rendering at all (Visualizer tab
        // hidden, Preferences open) reads as one slow frame, not a jump.
        let dt = self
            .last_render_instant
            .map(|prev| now.duration_since(prev).as_secs_f64().min(MAX_DT))
            .unwrap_or(0.0);
        self.last_render_instant = Some(now);

        let Some(compiled) = &self.compiled else {
            return;
        };
        let _ = compiled.lua.globals().set("DT", dt);

        let left: Vec<f32> = samples.iter().map(|&(l, _)| l).collect();
        let right: Vec<f32> = samples.iter().map(|&(_, r)| r).collect();

        let build_tables = (|| -> mlua::Result<(Table, Table)> {
            Ok((
                vec_to_table(&compiled.lua, &left)?,
                vec_to_table(&compiled.lua, &right)?,
            ))
        })();

        let outcome: mlua::Result<()> = match build_tables {
            Ok((left_table, right_table)) => compiled
                .render
                .call((width, height, left_table, right_table)),
            Err(e) => Err(e),
        };

        self.runtime_error = outcome.err().map(|e| e.to_string());
        if let Some(e) = &self.runtime_error {
            compiled.log.borrow_mut().push(LogLevel::Error, e.clone());
        }

        for cmd in compiled.commands.borrow_mut().drain(..) {
            rasterize(buffer, width, height, cmd);
        }
    }

    fn cursor_request(&self) -> CursorRequest {
        self.compiled.as_ref().map(|c| *c.cursor.borrow()).unwrap_or_default()
    }
}

#[allow(clippy::too_many_arguments)]
fn compile(
    source: &str,
    sample_rate: u32,
    spectrum_left: &Rc<RefCell<SpectrumAnalyzer>>,
    spectrum_right: &Rc<RefCell<SpectrumAnalyzer>>,
    notes: &Rc<RefCell<NotesSnapshot>>,
    playback: &Rc<RefCell<EngineView>>,
    input: &Rc<RefCell<VisualizerInput>>,
    pending_settings: HashMap<String, serde_json::Value>,
) -> Result<Compiled, String> {
    // No io/os/ffi/debug: a visualizer script has no legitimate reason to
    // touch the filesystem or spawn processes, even one the user just wrote.
    let libs = StdLib::TABLE | StdLib::STRING | StdLib::MATH;
    let lua = Lua::new_with(libs, LuaOptions::new()).map_err(|e| e.to_string())?;

    let commands: Rc<RefCell<Vec<DrawCommand>>> = Rc::new(RefCell::new(Vec::new()));
    let settings = Rc::new(RefCell::new(SettingsStore {
        descriptors: Vec::new(),
        pending: pending_settings,
    }));
    let log = Rc::new(RefCell::new(LogHistory::default()));
    let channel_requests: Rc<RefCell<Vec<(u8, bool)>>> = Rc::new(RefCell::new(Vec::new()));
    let debug_snapshot: Rc<RefCell<Option<DebugSnapshot>>> = Rc::new(RefCell::new(None));

    register_globals(
        &lua,
        sample_rate,
        &commands,
        spectrum_left,
        spectrum_right,
        notes,
        playback,
        &settings,
        &log,
        &channel_requests,
        &debug_snapshot,
    )
    .map_err(|e| e.to_string())?;
    let cursor = Rc::new(RefCell::new(CursorRequest::default()));
    register_input(&lua, input, &cursor).map_err(|e| e.to_string())?;

    lua.load(source)
        .set_name("visualizer")
        .exec()
        .map_err(|e| e.to_string())?;

    let render: Function = lua.globals().get("render").map_err(|_| {
        "script must define a `render(width, height, left, right)` function".to_string()
    })?;

    Ok(Compiled {
        source: source.to_string(),
        lua,
        render,
        commands,
        settings,
        log,
        channel_requests,
        debug_snapshot,
        cursor,
    })
}

/// The input and cursor functions: `mouse`, `mouse_delta`, `scroll`,
/// `mouse_down/pressed/released`, `key_down/pressed/released`, `has_focus`,
/// `display_mode`, `set_cursor_visible`, `set_cursor_locked`.
fn register_input(
    lua: &Lua,
    input: &Rc<RefCell<VisualizerInput>>,
    cursor: &Rc<RefCell<CursorRequest>>,
) -> mlua::Result<()> {
    let globals = lua.globals();

    let state = Rc::clone(input);
    globals.set(
        "mouse",
        lua.create_function(move |_, ()| {
            let pointer = state.borrow().pointer;
            Ok((pointer.map(|p| p.0), pointer.map(|p| p.1)))
        })?,
    )?;
    let state = Rc::clone(input);
    globals.set("mouse_delta", lua.create_function(move |_, ()| Ok(state.borrow().pointer_delta))?)?;
    let state = Rc::clone(input);
    globals.set("scroll", lua.create_function(move |_, ()| Ok(state.borrow().scroll))?)?;

    for (name, pick) in [
        ("mouse_down", 0usize),
        ("mouse_pressed", 1),
        ("mouse_released", 2),
    ] {
        let state = Rc::clone(input);
        globals.set(
            name,
            lua.create_function(move |_, button: Option<String>| {
                let index = parse_mouse_button(button.as_deref())?;
                let input = state.borrow();
                let buttons = match pick {
                    0 => &input.buttons_down,
                    1 => &input.buttons_pressed,
                    _ => &input.buttons_released,
                };
                Ok(buttons[index])
            })?,
        )?;
    }

    for (name, pick) in [("key_down", 0usize), ("key_pressed", 1), ("key_released", 2)] {
        let state = Rc::clone(input);
        globals.set(
            name,
            lua.create_function(move |_, key: String| {
                let Some(key) = parse_key(&key)? else {
                    return Ok(false); // reserved by the app, never reported
                };
                let input = state.borrow();
                let keys = match pick {
                    0 => &input.keys_down,
                    1 => &input.keys_pressed,
                    _ => &input.keys_released,
                };
                Ok(keys.contains(&key))
            })?,
        )?;
    }

    let state = Rc::clone(input);
    globals.set("has_focus", lua.create_function(move |_, ()| Ok(state.borrow().focused))?)?;
    let state = Rc::clone(input);
    globals.set("display_mode", lua.create_function(move |_, ()| Ok(state.borrow().mode.name()))?)?;

    let request = Rc::clone(cursor);
    globals.set(
        "set_cursor_visible",
        lua.create_function(move |_, visible: bool| {
            request.borrow_mut().hidden = !visible;
            Ok(())
        })?,
    )?;
    let request = Rc::clone(cursor);
    globals.set(
        "set_cursor_locked",
        lua.create_function(move |_, locked: bool| {
            request.borrow_mut().confined = locked;
            Ok(())
        })?,
    )?;
    Ok(())
}

/// "left" (also the default), "right" or "middle", as an index into
/// `VisualizerInput`'s button arrays.
fn parse_mouse_button(name: Option<&str>) -> mlua::Result<usize> {
    match name.map(str::to_ascii_lowercase).as_deref() {
        None | Some("left") => Ok(0),
        Some("right") => Ok(1),
        Some("middle") => Ok(2),
        Some(other) => Err(mlua::Error::runtime(format!(
            "unknown mouse button '{other}' (use \"left\", \"right\" or \"middle\")"
        ))),
    }
}

/// A key by name, case-insensitively ("a", "space", "up", "enter", "f5",
/// ...). `Ok(None)` for the app's reserved keys (Escape, F5, F11), which
/// scripts never see.
fn parse_key(name: &str) -> mlua::Result<Option<egui::Key>> {
    let key = egui::Key::ALL
        .iter()
        .copied()
        .find(|k| k.name().eq_ignore_ascii_case(name))
        .or_else(|| egui::Key::from_name(name))
        .ok_or_else(|| {
            mlua::Error::runtime(format!(
                "unknown key '{name}' (try e.g. \"a\", \"space\", \"up\", \"enter\")"
            ))
        })?;
    Ok((!RESERVED_KEYS.contains(&key)).then_some(key))
}

#[allow(clippy::too_many_arguments)]
fn register_globals(
    lua: &Lua,
    sample_rate: u32,
    commands: &Rc<RefCell<Vec<DrawCommand>>>,
    spectrum_left: &Rc<RefCell<SpectrumAnalyzer>>,
    spectrum_right: &Rc<RefCell<SpectrumAnalyzer>>,
    notes: &Rc<RefCell<NotesSnapshot>>,
    playback: &Rc<RefCell<EngineView>>,
    settings: &Rc<RefCell<SettingsStore>>,
    log: &Rc<RefCell<LogHistory>>,
    channel_requests: &Rc<RefCell<Vec<(u8, bool)>>>,
    debug_snapshot: &Rc<RefCell<Option<DebugSnapshot>>>,
) -> mlua::Result<()> {
    let globals = lua.globals();
    globals.set("SAMPLE_RATE", sample_rate)?;
    globals.set("NOTE_LOOKAHEAD", NOTE_LOOKAHEAD_SECS)?;
    globals.set("DT", 0.0)?;

    let cmds = Rc::clone(commands);
    globals.set(
        "clear",
        lua.create_function(move |_, color: Table| {
            cmds.borrow_mut().push(DrawCommand::Clear(table_to_color(&color)?));
            Ok(())
        })?,
    )?;

    let cmds = Rc::clone(commands);
    globals.set(
        "line",
        lua.create_function(
            move |_, (x0, y0, x1, y1, color): (f32, f32, f32, f32, Table)| {
                let color = table_to_color(&color)?;
                cmds.borrow_mut()
                    .push(DrawCommand::Line { x0, y0, x1, y1, color });
                Ok(())
            },
        )?,
    )?;

    let cmds = Rc::clone(commands);
    globals.set(
        "rect",
        lua.create_function(
            move |_, (x0, y0, x1, y1, color): (f32, f32, f32, f32, Table)| {
                let color = table_to_color(&color)?;
                cmds.borrow_mut()
                    .push(DrawCommand::Rect { x0, y0, x1, y1, color });
                Ok(())
            },
        )?,
    )?;

    let cmds = Rc::clone(commands);
    globals.set(
        "pixel",
        lua.create_function(move |_, (x, y, color): (i32, i32, Table)| {
            let color = table_to_color(&color)?;
            cmds.borrow_mut().push(DrawCommand::Pixel { x, y, color });
            Ok(())
        })?,
    )?;

    let active = Rc::clone(notes);
    globals.set(
        "active_notes",
        lua.create_function(move |lua, ()| {
            active_notes_to_table(lua, &active.borrow().active)
        })?,
    )?;

    let upcoming = Rc::clone(notes);
    globals.set(
        "upcoming_notes",
        lua.create_function(move |lua, ()| {
            upcoming_notes_to_table(lua, &upcoming.borrow().upcoming)
        })?,
    )?;

    let channels = Rc::clone(notes);
    globals.set(
        "midi_channels",
        lua.create_function(move |lua, ()| {
            let detected = &channels.borrow().detected_channels;
            let array = lua.create_table_with_capacity(detected.len(), 0)?;
            for (i, &c) in detected.iter().enumerate() {
                array.raw_set(i + 1, c)?;
            }
            Ok(array)
        })?,
    )?;

    let channels = Rc::clone(notes);
    globals.set(
        "channel_enabled",
        lua.create_function(move |_, channel: i64| {
            let notes = channels.borrow();
            if notes.detected_channels.is_empty() {
                return Ok(true); // nothing detected yet, don't filter anything
            }
            let index = channel.clamp(0, 15) as usize;
            Ok(notes.enabled_channels.get(index).copied().unwrap_or(true))
        })?,
    )?;

    let requests = Rc::clone(channel_requests);
    globals.set(
        "set_channel_enabled",
        lua.create_function(move |_, (channel, enabled): (i64, bool)| {
            requests.borrow_mut().push((channel.clamp(0, 15) as u8, enabled));
            Ok(())
        })?,
    )?;

    let left = Rc::clone(spectrum_left);
    globals.set(
        "fft_left",
        lua.create_function(move |lua, samples: Table| {
            let samples = table_to_vec(&samples)?;
            let magnitudes = left.borrow_mut().analyze(&samples);
            vec_to_table(lua, &magnitudes)
        })?,
    )?;

    let right = Rc::clone(spectrum_right);
    globals.set(
        "fft_right",
        lua.create_function(move |lua, samples: Table| {
            let samples = table_to_vec(&samples)?;
            let magnitudes = right.borrow_mut().analyze(&samples);
            vec_to_table(lua, &magnitudes)
        })?,
    )?;

    let view = Rc::clone(playback);
    globals.set(
        "playback",
        lua.create_function(move |lua, ()| {
            let view = view.borrow();
            let t = lua.create_table_with_capacity(0, 6)?;
            t.raw_set("position", view.position)?;
            t.raw_set("length", view.length)?;
            t.raw_set("speed", view.speed)?;
            t.raw_set("paused", view.paused)?;
            t.raw_set("finished", view.finished)?;
            t.raw_set("loop_enabled", view.loop_enabled)?;
            Ok(t)
        })?,
    )?;

    let history = Rc::clone(log);
    globals.set(
        "log",
        lua.create_function(move |_, message: String| {
            history.borrow_mut().push(LogLevel::Info, message);
            Ok(())
        })?,
    )?;

    // This does NOT grant the script Lua's own `debug` library
    // (StdLib::DEBUG is still excluded above), it's a host function that
    // happens to use the debug *C* API on the host side to read the calling
    // frame's locals, same trust boundary as every other host function here.
    let snapshot = Rc::clone(debug_snapshot);
    globals.set(
        "debug_locals",
        lua.create_function(move |lua, label: Option<String>| {
            let vars = capture_caller_locals(lua);
            *snapshot.borrow_mut() = Some(DebugSnapshot { label, vars });
            Ok(())
        })?,
    )?;

    let store = Rc::clone(settings);
    globals.set(
        "setting_bool",
        lua.create_function(move |_, (key, default): (String, bool)| {
            Ok(store.borrow_mut().get_or_register_bool(&key, default))
        })?,
    )?;

    let store = Rc::clone(settings);
    globals.set(
        "setting_int",
        lua.create_function(move |_, (key, default, min, max): (String, i64, i64, i64)| {
            Ok(store.borrow_mut().get_or_register_int(&key, default, min, max))
        })?,
    )?;

    let store = Rc::clone(settings);
    globals.set(
        "setting_float",
        lua.create_function(move |_, (key, default, min, max): (String, f64, f64, f64)| {
            Ok(store.borrow_mut().get_or_register_float(&key, default, min, max))
        })?,
    )?;

    let store = Rc::clone(settings);
    globals.set(
        "setting_color",
        lua.create_function(move |lua, (key, default): (String, Table)| {
            let default = table_to_rgb(&default)?;
            let value = store.borrow_mut().get_or_register_color(&key, default);
            rgb_to_table(lua, value)
        })?,
    )?;

    let store = Rc::clone(settings);
    globals.set(
        "setting_string",
        lua.create_function(move |_, (key, default): (String, String)| {
            Ok(store.borrow_mut().get_or_register_string(&key, &default))
        })?,
    )?;

    let store = Rc::clone(settings);
    globals.set(
        "setting_selection",
        lua.create_function(
            move |lua, (key, options, defaults, max_selections): (String, Table, Table, i64)| {
                let options = table_to_strings(&options)?;
                let defaults = table_to_strings(&defaults)?;
                let max_selections = max_selections.max(1) as usize;
                let value =
                    store.borrow_mut().get_or_register_selection(&key, options, defaults, max_selections);
                strings_to_table(lua, &value)
            },
        )?,
    )?;

    Ok(())
}

/// A color table `{r, g, b}` or `{r, g, b, a}` packed as `0xAARRGGBB`. `a` is
/// 0.0..1.0 and defaults to 1.0 (fully opaque, overwrites).
fn table_to_color(t: &Table) -> mlua::Result<u32> {
    let r: f32 = t.get("r")?;
    let g: f32 = t.get("g")?;
    let b: f32 = t.get("b")?;
    let a: Option<f32> = t.get("a")?;
    let byte = |v: f32| v.clamp(0.0, 255.0) as u32;
    let alpha = (a.unwrap_or(1.0).clamp(0.0, 1.0) * 255.0).round() as u32;
    Ok((alpha << 24) | (byte(r) << 16) | (byte(g) << 8) | byte(b))
}

/// A plain `{r, g, b}` table (no alpha) as used by `setting_color`.
fn table_to_rgb(t: &Table) -> mlua::Result<[u8; 3]> {
    let r: f32 = t.get("r")?;
    let g: f32 = t.get("g")?;
    let b: f32 = t.get("b")?;
    let byte = |v: f32| v.clamp(0.0, 255.0) as u8;
    Ok([byte(r), byte(g), byte(b)])
}

fn rgb_to_table(lua: &Lua, [r, g, b]: [u8; 3]) -> mlua::Result<Table> {
    let t = lua.create_table_with_capacity(0, 3)?;
    t.raw_set("r", r)?;
    t.raw_set("g", g)?;
    t.raw_set("b", b)?;
    Ok(t)
}

fn table_to_strings(t: &Table) -> mlua::Result<Vec<String>> {
    let len = t.raw_len();
    let mut out = Vec::with_capacity(len);
    for i in 1..=len {
        out.push(t.get(i)?);
    }
    Ok(out)
}

fn strings_to_table(lua: &Lua, values: &[String]) -> mlua::Result<Table> {
    let t = lua.create_table_with_capacity(values.len(), 0)?;
    for (i, v) in values.iter().enumerate() {
        t.raw_set(i + 1, v.clone())?;
    }
    Ok(t)
}

fn active_notes_to_table(lua: &Lua, notes: &[ActiveNote]) -> mlua::Result<Table> {
    let array = lua.create_table_with_capacity(notes.len(), 0)?;
    for (i, note) in notes.iter().enumerate() {
        let entry = lua.create_table_with_capacity(0, 3)?;
        entry.raw_set("channel", note.channel)?;
        entry.raw_set("key", note.key)?;
        entry.raw_set("velocity", note.velocity)?;
        array.raw_set(i + 1, entry)?;
    }
    Ok(array)
}

fn upcoming_notes_to_table(lua: &Lua, notes: &[NoteChange]) -> mlua::Result<Table> {
    let array = lua.create_table_with_capacity(notes.len(), 0)?;
    for (i, note) in notes.iter().enumerate() {
        let entry = lua.create_table_with_capacity(0, 5)?;
        entry.raw_set("channel", note.channel)?;
        entry.raw_set("key", note.key)?;
        entry.raw_set("velocity", note.velocity)?;
        entry.raw_set("on", note.on)?;
        entry.raw_set("seconds_until", note.seconds_until)?;
        array.raw_set(i + 1, entry)?;
    }
    Ok(array)
}

fn table_to_vec(t: &Table) -> mlua::Result<Vec<f32>> {
    let len = t.raw_len();
    let mut out = Vec::with_capacity(len);
    for i in 1..=len {
        out.push(t.get(i)?);
    }
    Ok(out)
}

fn vec_to_table(lua: &Lua, values: &[f32]) -> mlua::Result<Table> {
    let table = lua.create_table_with_capacity(values.len(), 0)?;
    for (i, &v) in values.iter().enumerate() {
        table.raw_set(i + 1, v)?;
    }
    Ok(table)
}

fn rasterize(buffer: &mut [u32], width: usize, height: usize, cmd: DrawCommand) {
    match cmd {
        // `clear` always overwrites (the alpha channel is dropped).
        DrawCommand::Clear(color) => buffer.fill(color & 0x00FF_FFFF),
        DrawCommand::Pixel { x, y, color } => set_pixel(buffer, width, height, x, y, color),
        DrawCommand::Line { x0, y0, x1, y1, color } => {
            draw_line(buffer, width, height, (x0, y0, x1, y1), color);
        }
        DrawCommand::Rect { x0, y0, x1, y1, color } => {
            fill_rect(buffer, width, height, (x0, y0, x1, y1), color);
        }
    }
}

/// Alpha-composite `src` (`0xAARRGGBB`) over `dst` (`0x00RRGGBB`), returning
/// `0x00RRGGBB`. `src` alpha 255 overwrites, 0 leaves `dst` untouched.
fn blend(dst: u32, src: u32) -> u32 {
    let a = src >> 24;
    if a >= 255 {
        return src & 0x00FF_FFFF;
    }
    if a == 0 {
        return dst;
    }
    let inv = 255 - a;
    let channel = |shift: u32| {
        let s = (src >> shift) & 0xFF;
        let d = (dst >> shift) & 0xFF;
        (s * a + d * inv + 127) / 255
    };
    (channel(16) << 16) | (channel(8) << 8) | channel(0)
}

/// Fill an axis-aligned rectangle, clipped to the buffer.
fn fill_rect(
    buffer: &mut [u32],
    width: usize,
    height: usize,
    (x0, y0, x1, y1): (f32, f32, f32, f32),
    color: u32,
) {
    let to_x = |v: f32| v.round().clamp(0.0, width as f32) as usize;
    let to_y = |v: f32| v.round().clamp(0.0, height as f32) as usize;
    let (xa, xb) = (to_x(x0.min(x1)), to_x(x0.max(x1)));
    let (ya, yb) = (to_y(y0.min(y1)), to_y(y0.max(y1)));
    let alpha = color >> 24;
    if alpha == 0 {
        return;
    }
    for y in ya..yb {
        let row = y * width;
        if alpha >= 255 {
            buffer[row + xa..row + xb].fill(color & 0x00FF_FFFF);
        } else {
            for pixel in &mut buffer[row + xa..row + xb] {
                *pixel = blend(*pixel, color);
            }
        }
    }
}

fn set_pixel(buffer: &mut [u32], width: usize, height: usize, x: i32, y: i32, color: u32) {
    if x < 0 || y < 0 || x as usize >= width || y as usize >= height {
        return;
    }
    let index = y as usize * width + x as usize;
    buffer[index] = blend(buffer[index], color);
}

/// Bresenham's line algorithm, in integer pixel space.
fn draw_line(
    buffer: &mut [u32],
    width: usize,
    height: usize,
    (x0, y0, x1, y1): (f32, f32, f32, f32),
    color: u32,
) {
    let (mut x0, mut y0) = (x0.round() as i32, y0.round() as i32);
    let (x1, y1) = (x1.round() as i32, y1.round() as i32);
    let dx = (x1 - x0).abs();
    let dy = -(y1 - y0).abs();
    let sx: i32 = if x0 < x1 { 1 } else { -1 };
    let sy: i32 = if y0 < y1 { 1 } else { -1 };
    let mut err = dx + dy;

    loop {
        set_pixel(buffer, width, height, x0, y0, color);
        if x0 == x1 && y0 == y1 {
            break;
        }
        let e2 = 2 * err;
        if e2 >= dy {
            err += dy;
            x0 += sx;
        }
        if e2 <= dx {
            err += dx;
            y0 += sy;
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sine_wave(freq: f32, sample_rate: f32, len: usize, phase: &mut f32) -> Vec<f32> {
        (0..len)
            .map(|_| {
                let sample = phase.sin();
                *phase += 2.0 * std::f32::consts::PI * freq / sample_rate;
                sample
            })
            .collect()
    }

    fn sample_notes() -> NotesSnapshot {
        NotesSnapshot {
            active: vec![
                ActiveNote { channel: 0, key: 60, velocity: 100 },
                ActiveNote { channel: 1, key: 64, velocity: 80 },
                ActiveNote { channel: 0, key: 21, velocity: 40 },
                ActiveNote { channel: 9, key: 108, velocity: 127 },
            ],
            upcoming: vec![
                NoteChange { channel: 0, key: 67, velocity: 90, on: true, seconds_until: 0.4 },
                NoteChange { channel: 0, key: 67, velocity: 0, on: false, seconds_until: 1.1 },
                NoteChange { channel: 2, key: 48, velocity: 70, on: true, seconds_until: 2.3 },
                // A note-on with no matching note-off inside the window.
                NoteChange { channel: 3, key: 84, velocity: 55, on: true, seconds_until: 3.7 },
            ],
            detected_channels: vec![0, 1, 2, 3, 9],
            // Channels 1 and 3 disabled, to exercise the two-pass path.
            enabled_channels: [
                true, false, true, false, true, true, true, true, true, true, true, true, true,
                true, true, true,
            ],
        }
    }

    fn sample_playback() -> EngineView {
        EngineView {
            track_name: Some("test".to_string()),
            soundfont_name: None,
            has_midi: true,
            has_audio_file: false,
            has_soundfont: true,
            position: 12.5,
            length: 180.0,
            speed: 1.0,
            paused: false,
            finished: false,
            loop_enabled: false,
        }
    }

    /// `debug_locals()` should capture real locals (and parameters, which
    /// `lua_getlocal` treats the same way) in scope at its call site,
    /// recurse into table values, and skip Lua's own internal temporaries.
    #[test]
    fn debug_locals_captures_scope_at_the_call_site() {
        let source = r#"
function render(width, height, left, right)
    local x = 42
    local label = "hello"
    local t = { a = 1, b = 2 }
    debug_locals("test point")
end
"#;
        let mut visualizer = LuaVisualizer::new(source.to_string(), None, 44_100);
        assert!(visualizer.error().is_none(), "failed to compile: {:?}", visualizer.error());
        assert!(visualizer.debug_snapshot().is_none(), "no snapshot before the first render");

        let mut buffer = vec![0u32; 16 * 16];
        visualizer.render(&mut buffer, 16, 16, &[], &NotesSnapshot::default(), &sample_playback(), &VisualizerInput::default());

        let snapshot = visualizer.debug_snapshot().expect("debug_locals should have captured a snapshot");
        assert_eq!(snapshot.label.as_deref(), Some("test point"));

        let find = |name: &str| snapshot.vars.iter().find(|v| v.name == name);
        assert_eq!(find("x").map(|v| v.value.as_str()), Some("42"));
        assert_eq!(find("label").map(|v| v.value.as_str()), Some("\"hello\""));
        let t = find("t").expect("table local `t` should be captured");
        assert_eq!(t.children.len(), 2, "t = {{a=1, b=2}} should have 2 entries");
    }

    /// Feed a bundled default script several frames of synthetic audio + note
    /// data and make sure it compiles and never hits a Lua runtime error, a
    /// script shipped as a default should never itself be the thing showing
    /// an error banner. `name` is just for a clearer panic message when this
    /// runs over every bundled script in a loop.
    fn assert_script_runs_cleanly(name: &str, source: &str, notes: &NotesSnapshot) {
        let mut visualizer = LuaVisualizer::new(source.to_string(), None, 44_100);
        assert!(
            visualizer.error().is_none(),
            "{name}: failed to compile: {:?}",
            visualizer.error()
        );

        let mut buffer = vec![0u32; 64 * 32];
        let mut phase = 0.0f32;
        let playback = sample_playback();
        for _ in 0..8 {
            let mono = sine_wave(440.0, 44_100.0, 512, &mut phase);
            let samples: Vec<StereoFrame> = mono.iter().map(|&s| (s, s)).collect();
            visualizer.render(&mut buffer, 64, 32, &samples, notes, &playback, &VisualizerInput::default());
            assert!(
                visualizer.error().is_none(),
                "{name}: runtime error: {:?}",
                visualizer.error()
            );
        }
    }

    /// Every bundled script, dropped or not, against both the empty and
    /// the populated note paths, with no per-script test function to
    /// remember to add: `build.rs` already means a new file under
    /// `assets/visualizers/{dropped,undropped}` needs no Rust-side edit to
    /// be picked up as a script; this is the same guarantee for its tests.
    #[test]
    fn bundled_scripts_run_cleanly() {
        for &(name, source) in DROPPED_SCRIPTS.iter().chain(UNDROPPED_SCRIPTS) {
            assert_script_runs_cleanly(name, source, &NotesSnapshot::default());
            assert_script_runs_cleanly(name, source, &sample_notes());
        }
    }

    #[test]
    fn blank_script_template_runs_cleanly() {
        assert_script_runs_cleanly("blank template", BLANK_SCRIPT_TEMPLATE, &NotesSnapshot::default());
    }

    /// Looks up a bundled script's source by file name, for tests that
    /// exercise one specific script's behavior rather than every script
    /// generically.
    fn find_script(file_name: &str) -> &'static str {
        DROPPED_SCRIPTS
            .iter()
            .chain(UNDROPPED_SCRIPTS)
            .find(|&&(name, _)| name == file_name)
            .map(|&(_, source)| source)
            .unwrap_or_else(|| panic!("no bundled script named {file_name}"))
    }

    /// A bad edit's compile error must stay visible through `error()` even
    /// after the still-running (older) script renders several more
    /// successful frames. This was the actual reported bug: the error
    /// disappeared within one frame because a successful render from the
    /// fallback script was clearing it.
    #[test]
    fn input_functions_see_the_frames_input() {
        let script = r#"
function render(w, h, l, r)
    local x, y = mouse()
    log("mouse " .. tostring(x) .. " " .. tostring(y))
    log("left " .. tostring(mouse_down()) .. " right " .. tostring(mouse_pressed("right")))
    log("a " .. tostring(key_down("A")) .. " space " .. tostring(key_pressed("space")) .. " esc " .. tostring(key_down("escape")))
    log("focus " .. tostring(has_focus()) .. " mode " .. display_mode())
    set_cursor_visible(false)
    set_cursor_locked(true)
end"#;
        let mut visualizer = LuaVisualizer::new(script.to_string(), None, 44_100);
        assert_eq!(visualizer.cursor_request(), CursorRequest::default());
        let input = VisualizerInput {
            mode: crate::visualizer::DisplayMode::Dedicated,
            focused: true,
            pointer: Some((3.0, 4.0)),
            buttons_down: [true, false, false],
            buttons_pressed: [false, true, false],
            keys_down: vec![egui::Key::A, egui::Key::Escape],
            keys_pressed: vec![egui::Key::Space],
            ..Default::default()
        };
        let mut buffer = vec![0u32; 16 * 16];
        visualizer.render(&mut buffer, 16, 16, &[], &NotesSnapshot::default(), &sample_playback(), &input);
        assert_eq!(visualizer.error(), None);

        let messages: Vec<String> = visualizer.log_entries().into_iter().map(|e| e.message).collect();
        assert_eq!(
            messages,
            [
                "mouse 3.0 4.0",
                "left true right true",
                "a true space true esc false",
                "focus true mode dedicated",
            ]
        );
        assert_eq!(visualizer.cursor_request(), CursorRequest { hidden: true, confined: true });
    }

    #[test]
    fn restart_runs_the_running_script_fresh_even_after_a_broken_edit() {
        let script = "local frames = 0
function render(w, h, l, r) frames = frames + 1; log('frame ' .. frames) end";
        let mut visualizer = LuaVisualizer::new(script.to_string(), None, 44_100);
        let mut buffer = vec![0u32; 4];
        let mut frame = |v: &mut LuaVisualizer| {
            v.render(&mut buffer, 2, 2, &[], &NotesSnapshot::default(), &sample_playback(), &VisualizerInput::default());
        };
        frame(&mut visualizer);
        frame(&mut visualizer);
        assert_eq!(visualizer.log_entries().last().unwrap().message, "frame 2");

        // A broken edit leaves the old script running; restarting restarts
        // that one, and the edit's error stays reported.
        visualizer.set_source("function render(".to_string());
        assert!(visualizer.restart());
        frame(&mut visualizer);
        assert_eq!(visualizer.log_entries().last().unwrap().message, "frame 1");
        assert!(visualizer.error().is_some());
    }

    #[test]
    fn reserved_keys_never_reach_scripts() {
        let script = "function render(w, h, l, r) log(tostring(key_down('escape')) .. tostring(key_down('f5')) .. tostring(key_down('F11')) .. tostring(key_down('f6'))) end";
        let mut visualizer = LuaVisualizer::new(script.to_string(), None, 44_100);
        let input = VisualizerInput {
            focused: true,
            keys_down: vec![egui::Key::Escape, egui::Key::F5, egui::Key::F11, egui::Key::F6],
            ..Default::default()
        };
        let mut buffer = vec![0u32; 4];
        visualizer.render(&mut buffer, 2, 2, &[], &NotesSnapshot::default(), &sample_playback(), &input);
        assert_eq!(visualizer.log_entries().last().unwrap().message, "falsefalsefalsetrue");
    }

    #[test]
    fn unknown_keys_and_buttons_are_script_errors() {
        for call in ["key_down('nope')", "mouse_down('thumb')"] {
            let script = format!("function render(w, h, l, r) {call} end");
            let mut visualizer = LuaVisualizer::new(script, None, 44_100);
            let mut buffer = vec![0u32; 4];
            visualizer.render(&mut buffer, 2, 2, &[], &NotesSnapshot::default(), &sample_playback(), &VisualizerInput::default());
            let error = visualizer.error().unwrap_or_default().to_string();
            assert!(error.contains("unknown"), "{call}: {error}");
        }
    }

    #[test]
    fn compile_error_persists_across_successful_renders() {
        let mut visualizer = LuaVisualizer::new(BLANK_SCRIPT_TEMPLATE.to_string(), None, 44_100);
        assert!(visualizer.error().is_none());

        visualizer.set_source("this is not valid lua(".to_string());
        assert!(visualizer.error().is_some(), "a bad edit should report an error");

        let mut buffer = vec![0u32; 16 * 16];
        let playback = sample_playback();
        for _ in 0..5 {
            visualizer.render(&mut buffer, 16, 16, &[], &NotesSnapshot::default(), &playback, &VisualizerInput::default());
            assert!(
                visualizer.error().is_some(),
                "a successful render of the fallback script must not clear the standing compile error"
            );
        }

        // Fixing it should clear the standing error.
        visualizer.set_source(BLANK_SCRIPT_TEMPLATE.to_string());
        assert!(visualizer.error().is_none());
    }

    /// A compile error should also land in the (still-running) script's own
    /// log, not just the transient inline banner.
    #[test]
    fn compile_error_is_logged_against_the_running_script() {
        let mut visualizer = LuaVisualizer::new(BLANK_SCRIPT_TEMPLATE.to_string(), None, 44_100);
        visualizer.set_source("this is not valid lua(".to_string());
        let entries = visualizer.log_entries();
        assert!(
            entries.iter().any(|e| e.level == LogLevel::Error && e.message.contains("compile error")),
            "expected a compile-error entry in the log, got: {entries:?}"
        );
    }

    /// A script's registered settings should reflect its declared defaults
    /// the first time it runs, with no sidecar file present.
    #[test]
    fn settings_demo_registers_expected_defaults() {
        let mut visualizer = LuaVisualizer::new(find_script("settings_demo.lua").to_string(), None, 44_100);
        let mut buffer = vec![0u32; 16 * 16];
        visualizer.render(&mut buffer, 16, 16, &[], &NotesSnapshot::default(), &sample_playback(), &VisualizerInput::default());
        let settings = visualizer.settings();
        assert!(!settings.is_empty(), "settings_demo.lua should register settings");
        assert!(settings.iter().any(|d| matches!(d.kind, SettingKind::Bool)));
        assert!(settings.iter().any(|d| matches!(d.kind, SettingKind::Int { .. })));
        assert!(settings.iter().any(|d| matches!(d.kind, SettingKind::Float { .. })));
        assert!(settings.iter().any(|d| matches!(d.kind, SettingKind::Color)));
        assert!(settings.iter().any(|d| matches!(d.kind, SettingKind::String)));
        assert!(settings.iter().any(|d| matches!(d.kind, SettingKind::Selection { .. })));
    }

    /// Changing a setting through `set_setting` should be visible to the
    /// script on the very next frame, with no recompile.
    #[test]
    fn set_setting_applies_without_recompile() {
        let mut visualizer = LuaVisualizer::new(find_script("settings_demo.lua").to_string(), None, 44_100);
        let mut buffer = vec![0u32; 16 * 16];
        let playback = sample_playback();
        visualizer.render(&mut buffer, 16, 16, &[], &NotesSnapshot::default(), &playback, &VisualizerInput::default());

        let bool_key = visualizer
            .settings()
            .iter()
            .find(|d| matches!(d.kind, SettingKind::Bool))
            .map(|d| d.key.clone())
            .expect("settings_demo.lua should have a bool setting");

        visualizer.set_setting(&bool_key, SettingValue::Bool(true));
        visualizer.render(&mut buffer, 16, 16, &[], &NotesSnapshot::default(), &playback, &VisualizerInput::default());
        let value = visualizer
            .settings()
            .into_iter()
            .find(|d| d.key == bool_key)
            .map(|d| d.value)
            .unwrap();
        assert!(matches!(value, SettingValue::Bool(true)));
    }

    /// Not a correctness test, prints how long a `render` call takes for each
    /// bundled script at the app's actual panel size (800x320), with a
    /// realistic worst-case sample count (two audio chunks landing between two
    /// 60fps frames) and a busy note load, so there's a real number behind
    /// "does this keep up at 60fps" rather than a guess. Run with
    /// `cargo test --bin synththing -- --ignored --nocapture`.
    #[test]
    #[ignore = "prints timing, not a pass/fail check"]
    fn bundled_script_render_timing() {
        // ~32 notes held, ~64 upcoming changes, a dense passage.
        let notes = {
            let mut snapshot = NotesSnapshot::default();
            for i in 0..32u8 {
                snapshot.active.push(ActiveNote {
                    channel: i % 6,
                    key: 30 + i * 2,
                    velocity: 90,
                });
            }
            for i in 0..64u8 {
                snapshot.upcoming.push(NoteChange {
                    channel: i % 6,
                    key: 24 + i,
                    velocity: if i % 2 == 0 { 90 } else { 0 },
                    on: i % 2 == 0,
                    seconds_until: 0.1 + i as f32 * 0.05,
                });
            }
            snapshot.detected_channels = vec![0, 1, 2, 3, 4, 5];
            // Half the channels disabled → the keyboard's translucent second
            // pass does per-pixel blending, the slower path.
            snapshot.enabled_channels = [
                true, false, true, false, true, false, true, true, true, true, true, true, true,
                true, true, true,
            ];
            snapshot
        };
        let playback = sample_playback();

        for &(name, source) in DROPPED_SCRIPTS.iter().chain(UNDROPPED_SCRIPTS) {
            let mut visualizer = LuaVisualizer::new(source.to_string(), None, 44_100);
            assert!(visualizer.error().is_none());

            let mut buffer = vec![0u32; 800 * 320];
            let mut phase = 0.0f32;
            let mut frame = |v: &mut LuaVisualizer| {
                let mono = sine_wave(440.0, 44_100.0, 2048, &mut phase);
                let samples: Vec<StereoFrame> = mono.iter().map(|&s| (s, s)).collect();
                v.render(&mut buffer, 800, 320, &samples, &notes, &playback, &VisualizerInput::default());
            };

            for _ in 0..8 {
                frame(&mut visualizer);
            }
            let frames = 120;
            let start = std::time::Instant::now();
            for _ in 0..frames {
                frame(&mut visualizer);
            }
            println!(
                "{name}: {:.3}ms/frame over {frames} frames (60fps budget: 16.7ms)",
                start.elapsed().as_secs_f64() * 1000.0 / frames as f64
            );
            assert!(visualizer.error().is_none());
        }
    }
}
