//! The in-app scripting reference (the Scripting Reference tab, View menu).
//!
//! The content lives in `docs/scripting-reference.md`, a normal Markdown
//! file that reads fine on GitHub or handed to anything else. `build.rs`
//! parses it at build time (a small subset: `##` sections, paragraphs,
//! fenced code, `-` bullets, inline `code`) into the `SECTIONS` table
//! below, which `app.rs` renders with egui's own widgets. Edit the
//! Markdown, not this file.

pub struct Section {
    pub title: &'static str,
    pub blocks: &'static [Block],
}

pub enum Block {
    /// A paragraph, possibly with `inline code` (see `inline_spans`).
    P(&'static str),
    Code(&'static str),
    Bullets(&'static [&'static str]),
}

// SECTIONS: &[Section], generated by build.rs from docs/scripting-reference.md.
include!(concat!(env!("OUT_DIR"), "/scripting_reference.rs"));

pub fn sections() -> &'static [Section] {
    SECTIONS
}

/// Where `name` (a function or global) is documented: (section, block).
/// Its own line in a code block (`rect(x0, ...)`, `FONT_HEIGHT -- 12`)
/// wins; otherwise the first place text mentions it as `name`.
pub fn find(name: &str) -> Option<(usize, usize)> {
    let defines = |code: &str| {
        code.lines().any(|line| {
            let line = line.trim_start();
            line.strip_prefix(name)
                .is_some_and(|rest| rest.is_empty() || rest.starts_with('(') || rest.starts_with(char::is_whitespace))
        })
    };
    let mentions = |text: &str| text.contains(&format!("`{name}`")) || text.contains(&format!("`{name}("));
    let mut mentioned = None;
    for (s, section) in SECTIONS.iter().enumerate() {
        for (b, block) in section.blocks.iter().enumerate() {
            match block {
                Block::Code(code) if defines(code) => return Some((s, b)),
                Block::P(text) if mentioned.is_none() && mentions(text) => mentioned = Some((s, b)),
                Block::Bullets(items) if mentioned.is_none() && items.iter().any(|i| mentions(i)) => {
                    mentioned = Some((s, b))
                }
                _ => {}
            }
        }
    }
    mentioned
}

/// Split paragraph or bullet text into `(text, is_code)` spans at its
/// backticks, so `inline code` can be drawn in a monospace font.
pub fn inline_spans(text: &str) -> impl Iterator<Item = (&str, bool)> {
    text.split('`').enumerate().filter(|(_, s)| !s.is_empty()).map(|(i, s)| (s, i % 2 == 1))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_host_function_is_documented() {
        for (name, _) in crate::lua_completion::HOST_API {
            assert!(find(name).is_some(), "{name} isn't in docs/scripting-reference.md");
        }
        let (section, _) = find("rect").unwrap();
        assert_eq!(sections()[section].title, "Drawing");
        // The examples section comes after the API, so links go to each
        // function's own definition, not its example.
        for (name, _) in crate::lua_completion::HOST_API {
            let (section, _) = find(name).unwrap();
            assert_ne!(sections()[section].title, "Example calls and results", "{name}");
        }
    }

    #[test]
    fn the_markdown_reference_parses_into_sections() {
        let titles: Vec<&str> = sections().iter().map(|s| s.title).collect();
        for expected in ["Getting started", "Drawing", "Input", "Settings", "Bundled scripts, as reference"] {
            assert!(titles.contains(&expected), "missing section {expected:?} in {titles:?}");
        }
        for section in sections() {
            assert!(!section.blocks.is_empty(), "empty section {:?}", section.title);
            for block in section.blocks {
                match block {
                    // Paragraphs are joined into one line; no stray
                    // newlines or runs of spaces from the source wrapping.
                    Block::P(text) => {
                        assert!(!text.contains('\n') && !text.contains("  "), "{text:?}");
                        assert_eq!(text.matches('`').count() % 2, 0, "unbalanced backticks: {text:?}");
                    }
                    Block::Code(code) => assert!(!code.trim().is_empty()),
                    Block::Bullets(items) => assert!(items.iter().all(|i| !i.trim().is_empty())),
                }
            }
        }
        // Code blocks keep their line structure.
        let input = sections().iter().find(|s| s.title == "Input").unwrap();
        assert!(input.blocks.iter().any(|b| matches!(b, Block::Code(c) if c.lines().count() > 5 && c.contains("mouse()"))));
    }

    #[test]
    fn inline_code_spans() {
        let spans: Vec<_> = inline_spans("call `render()` per frame").collect();
        assert_eq!(spans, [("call ", false), ("render()", true), (" per frame", false)]);
    }
}
